M48
; DRILL file {KiCad 9.0.7} date 2026-09-21T22:58:01+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T22:58:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X192.29Y-113.76
X197.14Y-113.76
T2
X191.99Y-116.79
X197.44Y-116.79
T3
X210.8Y-71.2
X210.8Y-110.6
M30
